[package]
name = "mb-api"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "api"
path = "src/main.rs"

[dependencies]
mb-core.workspace = true
mb-identity.workspace = true
mb-namespaces.workspace = true
mb-schema-registry.workspace = true
mb-mixins.workspace = true
mb-profile.workspace = true
mb-events.workspace = true
mb-audiences.workspace = true
mb-connectors.workspace = true
mb-governance.workspace = true
mb-channels.workspace = true
mb-templates.workspace = true
mb-journeys.workspace = true
tokio.workspace = true
axum.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
chrono.workspace = true
thiserror.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
sqlx.workspace = true
